export const healthyMeals = [
  {
    id: 1,
    title: "Grilled Salmon with Quinoa & Steamed Broccoli",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=80",
    description: "Omega-3 rich grilled salmon served with protein-packed quinoa and fiber-rich steamed broccoli.",
    calories: 520,
    protein: 45,
    carbs: 35,
    fat: 18,
    diets: ["pescatarian", "gluten free"],
    cuisines: ["American"],
    prepTime: 30,
  },
  {
    id: 2,
    title: "Mediterranean Chicken Bowl",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80",
    description: "Herb-marinated grilled chicken with quinoa, cucumber, tomatoes, olives, and tzatziki sauce.",
    calories: 485,
    protein: 42,
    carbs: 38,
    fat: 16,
    diets: ["gluten free"],
    cuisines: ["Mediterranean"],
    prepTime: 25,
  },
  {
    id: 3,
    title: "Avocado Toast with Poached Egg",
    image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?auto=format&fit=crop&w=600&q=80",
    description: "Whole grain toast topped with smashed avocado, perfectly poached egg, and microgreens.",
    calories: 380,
    protein: 18,
    carbs: 28,
    fat: 22,
    diets: ["vegetarian"],
    cuisines: ["American"],
    prepTime: 15,
  },
  {
    id: 4,
    title: "Thai Coconut Curry with Tofu",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=600&q=80",
    description: "Aromatic coconut curry with crispy tofu, bell peppers, and jasmine rice.",
    calories: 450,
    protein: 24,
    carbs: 52,
    fat: 19,
    diets: ["vegan", "gluten free"],
    cuisines: ["Thai"],
    prepTime: 35,
  },
  {
    id: 5,
    title: "Greek Yogurt Berry Parfait",
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=600&q=80",
    description: "Protein-rich Greek yogurt layered with mixed berries and homemade granola.",
    calories: 320,
    protein: 20,
    carbs: 42,
    fat: 8,
    diets: ["vegetarian", "gluten free"],
    cuisines: ["Greek"],
    prepTime: 10,
  },
  {
    id: 6,
    title: "Quinoa Stuffed Bell Peppers",
    image: "https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?auto=format&fit=crop&w=600&q=80",
    description: "Colorful bell peppers stuffed with quinoa, black beans, corn, and topped with cheese.",
    calories: 395,
    protein: 18,
    carbs: 48,
    fat: 14,
    diets: ["vegetarian", "gluten free"],
    cuisines: ["Mexican"],
    prepTime: 45,
  },
  {
    id: 7,
    title: "Teriyaki Chicken with Brown Rice",
    image: "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?auto=format&fit=crop&w=600&q=80",
    description: "Lean chicken breast glazed with homemade teriyaki sauce, served with brown rice and steamed vegetables.",
    calories: 465,
    protein: 38,
    carbs: 45,
    fat: 12,
    diets: ["gluten free"],
    cuisines: ["Japanese"],
    prepTime: 30,
  },
  {
    id: 8,
    title: "Lentil and Vegetable Soup",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80",
    description: "Hearty soup packed with red lentils, carrots, celery, spinach, and aromatic herbs.",
    calories: 285,
    protein: 18,
    carbs: 48,
    fat: 3,
    diets: ["vegan", "gluten free"],
    cuisines: ["Mediterranean"],
    prepTime: 40,
  },
  {
    id: 9,
    title: "Seared Tuna with Sesame Seeds",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80",
    description: "Sushi-grade tuna seared to perfection with sesame seeds, served with mixed greens and wasabi.",
    calories: 340,
    protein: 42,
    carbs: 8,
    fat: 16,
    diets: ["pescatarian", "gluten free"],
    cuisines: ["Japanese"],
    prepTime: 20,
  },
  {
    id: 10,
    title: "Sweet Potato and Black Bean Burrito Bowl",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=600&q=80",
    description: "Roasted sweet potato with black beans, corn, avocado, and cilantro lime dressing.",
    calories: 425,
    protein: 16,
    carbs: 68,
    fat: 12,
    diets: ["vegan", "gluten free"],
    cuisines: ["Mexican"],
    prepTime: 35,
  },
  {
    id: 11,
    title: "Cauliflower Rice Stir-Fry",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80",
    description: "Low-carb cauliflower rice stir-fried with mixed vegetables, eggs, and soy sauce.",
    calories: 245,
    protein: 12,
    carbs: 18,
    fat: 14,
    diets: ["vegetarian", "gluten free", "keto"],
    cuisines: ["Asian"],
    prepTime: 20,
  },
  {
    id: 12,
    title: "Moroccan Chickpea Tagine",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=600&q=80",
    description: "Aromatic chickpea stew with apricots, almonds, and traditional Moroccan spices.",
    calories: 380,
    protein: 15,
    carbs: 58,
    fat: 11,
    diets: ["vegan", "gluten free"],
    cuisines: ["Moroccan"],
    prepTime: 50,
  },
  {
    id: 13,
    title: "Zucchini Noodles with Pesto",
    image: "https://images.unsplash.com/photo-1551248429-40975aa4de74?auto=format&fit=crop&w=600&q=80",
    description: "Spiralized zucchini noodles tossed with homemade basil pesto and cherry tomatoes.",
    calories: 220,
    protein: 8,
    carbs: 12,
    fat: 18,
    diets: ["vegetarian", "gluten free", "keto"],
    cuisines: ["Italian"],
    prepTime: 15,
  },
  {
    id: 14,
    title: "Baked Cod with Lemon Herbs",
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=600&q=80",
    description: "Flaky white cod baked with fresh herbs, lemon, and served with roasted asparagus.",
    calories: 295,
    protein: 35,
    carbs: 8,
    fat: 14,
    diets: ["pescatarian", "gluten free", "keto"],
    cuisines: ["European"],
    prepTime: 25,
  },
  {
    id: 15,
    title: "Buddha Bowl with Tahini Dressing",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80",
    description: "Nourishing bowl with quinoa, roasted vegetables, chickpeas, and creamy tahini dressing.",
    calories: 485,
    protein: 18,
    carbs: 62,
    fat: 19,
    diets: ["vegan", "gluten free"],
    cuisines: ["Middle Eastern"],
    prepTime: 40,
  },
  {
    id: 16,
    title: "Turkey and Vegetable Meatballs",
    image: "https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=600&q=80",
    description: "Lean turkey meatballs with hidden vegetables, served with marinara sauce and zucchini noodles.",
    calories: 365,
    protein: 32,
    carbs: 18,
    fat: 18,
    diets: ["gluten free"],
    cuisines: ["Italian"],
    prepTime: 35,
  },
  {
    id: 17,
    title: "Korean Bibimbap Bowl",
    image: "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?auto=format&fit=crop&w=600&q=80",
    description: "Traditional Korean rice bowl with seasoned vegetables, beef, and gochujang sauce.",
    calories: 520,
    protein: 28,
    carbs: 65,
    fat: 16,
    diets: ["gluten free"],
    cuisines: ["Korean"],
    prepTime: 45,
  },
  {
    id: 18,
    title: "Chia Seed Pudding with Mango",
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=600&q=80",
    description: "Overnight chia pudding with coconut milk, topped with fresh mango and toasted coconut.",
    calories: 285,
    protein: 8,
    carbs: 32,
    fat: 16,
    diets: ["vegan", "gluten free"],
    cuisines: ["Tropical"],
    prepTime: 10,
  },
  {
    id: 19,
    title: "Stuffed Portobello Mushrooms",
    image: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?auto=format&fit=crop&w=600&q=80",
    description: "Large portobello caps stuffed with spinach, sun-dried tomatoes, and goat cheese.",
    calories: 245,
    protein: 14,
    carbs: 12,
    fat: 18,
    diets: ["vegetarian", "gluten free", "keto"],
    cuisines: ["Mediterranean"],
    prepTime: 30,
  },
  {
    id: 20,
    title: "Vietnamese Pho with Chicken",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80",
    description: "Aromatic broth with rice noodles, tender chicken, herbs, and fresh vegetables.",
    calories: 395,
    protein: 28,
    carbs: 48,
    fat: 8,
    diets: ["gluten free"],
    cuisines: ["Vietnamese"],
    prepTime: 60,
  },
  {
    id: 21,
    title: "Spinach and Feta Stuffed Chicken",
    image: "https://images.unsplash.com/photo-1532636875304-0c89119d9b4d?auto=format&fit=crop&w=600&q=80",
    description: "Juicy chicken breast stuffed with spinach and feta, served with roasted sweet potato.",
    calories: 445,
    protein: 42,
    carbs: 28,
    fat: 19,
    diets: ["gluten free"],
    cuisines: ["Greek"],
    prepTime: 40,
  },
  {
    id: 22,
    title: "Black Bean and Quinoa Salad",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80",
    description: "Protein-rich salad with black beans, quinoa, corn, tomatoes, and lime vinaigrette.",
    calories: 365,
    protein: 16,
    carbs: 58,
    fat: 9,
    diets: ["vegan", "gluten free"],
    cuisines: ["Mexican"],
    prepTime: 20,
  },
  {
    id: 23,
    title: "Miso Glazed Eggplant",
    image: "https://images.unsplash.com/photo-1576402794548-1a3bf9049ce1?auto=format&fit=crop&w=600&q=80",
    description: "Japanese-style eggplant glazed with miso paste, served with steamed edamame.",
    calories: 285,
    protein: 12,
    carbs: 35,
    fat: 12,
    diets: ["vegan", "gluten free"],
    cuisines: ["Japanese"],
    prepTime: 25,
  },
  {
    id: 24,
    title: "Turkey Lettuce Wraps",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?auto=format&fit=crop&w=600&q=80",
    description: "Asian-inspired ground turkey wrapped in crisp lettuce leaves with water chestnuts.",
    calories: 245,
    protein: 28,
    carbs: 12,
    fat: 10,
    diets: ["gluten free", "keto"],
    cuisines: ["Asian"],
    prepTime: 20,
  },
  {
    id: 25,
    title: "Roasted Vegetable and Hummus Wrap",
    image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=600&q=80",
    description: "Whole wheat wrap filled with roasted vegetables, hummus, and fresh herbs.",
    calories: 385,
    protein: 14,
    carbs: 58,
    fat: 12,
    diets: ["vegan"],
    cuisines: ["Mediterranean"],
    prepTime: 30,
  },
  {
    id: 26,
    title: "Salmon Poke Bowl",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80",
    description: "Fresh salmon sashimi over brown rice with avocado, cucumber, and seaweed salad.",
    calories: 485,
    protein: 35,
    carbs: 42,
    fat: 20,
    diets: ["pescatarian", "gluten free"],
    cuisines: ["Hawaiian"],
    prepTime: 15,
  },
  {
    id: 27,
    title: "Butternut Squash Soup",
    image: "https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?auto=format&fit=crop&w=600&q=80",
    description: "Creamy butternut squash soup with ginger, coconut milk, and toasted pumpkin seeds.",
    calories: 225,
    protein: 6,
    carbs: 32,
    fat: 9,
    diets: ["vegan", "gluten free"],
    cuisines: ["American"],
    prepTime: 45,
  },
  {
    id: 28,
    title: "Herb-Crusted Lamb Chops",
    image: "https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=600&q=80",
    description: "Tender lamb chops with herb crust, served with roasted root vegetables.",
    calories: 485,
    protein: 38,
    carbs: 18,
    fat: 28,
    diets: ["gluten free", "keto"],
    cuisines: ["French"],
    prepTime: 35,
  },
  {
    id: 29,
    title: "Tempeh Tacos with Cabbage Slaw",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?auto=format&fit=crop&w=600&q=80",
    description: "Crispy tempeh in corn tortillas with crunchy cabbage slaw and avocado.",
    calories: 385,
    protein: 18,
    carbs: 45,
    fat: 16,
    diets: ["vegan", "gluten free"],
    cuisines: ["Mexican"],
    prepTime: 25,
  },
  {
    id: 30,
    title: "Baked Sweet Potato with Black Beans",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=600&q=80",
    description: "Fluffy baked sweet potato topped with seasoned black beans and Greek yogurt.",
    calories: 345,
    protein: 14,
    carbs: 62,
    fat: 6,
    diets: ["vegetarian", "gluten free"],
    cuisines: ["American"],
    prepTime: 35,
  },
  {
    id: 31,
    title: "Indian Lentil Dal",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=600&q=80",
    description: "Spiced yellow lentils cooked with turmeric, cumin, and served with brown rice.",
    calories: 325,
    protein: 18,
    carbs: 52,
    fat: 6,
    diets: ["vegan", "gluten free"],
    cuisines: ["Indian"],
    prepTime: 40,
  },
  {
    id: 32,
    title: "Grilled Vegetable Skewers",
    image: "https://images.unsplash.com/photo-1551248429-40975aa4de74?auto=format&fit=crop&w=600&q=80",
    description: "Colorful vegetables grilled on skewers with herbs and served with quinoa pilaf.",
    calories: 285,
    protein: 12,
    carbs: 48,
    fat: 8,
    diets: ["vegan", "gluten free"],
    cuisines: ["Mediterranean"],
    prepTime: 30,
  },
  {
    id: 33,
    title: "Chicken and Vegetable Curry",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=600&q=80",
    description: "Mild chicken curry with mixed vegetables in coconut milk, served with basmati rice.",
    calories: 465,
    protein: 35,
    carbs: 48,
    fat: 16,
    diets: ["gluten free"],
    cuisines: ["Indian"],
    prepTime: 45,
  },
  {
    id: 34,
    title: "Stuffed Zucchini Boats",
    image: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?auto=format&fit=crop&w=600&q=80",
    description: "Hollowed zucchini filled with turkey, tomatoes, and topped with mozzarella cheese.",
    calories: 325,
    protein: 28,
    carbs: 12,
    fat: 18,
    diets: ["gluten free", "keto"],
    cuisines: ["Italian"],
    prepTime: 40,
  },
  {
    id: 35,
    title: "Quinoa Breakfast Bowl",
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=600&q=80",
    description: "Warm quinoa porridge with almond milk, berries, nuts, and a drizzle of honey.",
    calories: 365,
    protein: 12,
    carbs: 58,
    fat: 11,
    diets: ["vegetarian", "gluten free"],
    cuisines: ["American"],
    prepTime: 15,
  },
  {
    id: 36,
    title: "Mediterranean Sardine Salad",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80",
    description: "Omega-3 rich sardines with mixed greens, olives, tomatoes, and lemon vinaigrette.",
    calories: 285,
    protein: 24,
    carbs: 12,
    fat: 18,
    diets: ["pescatarian", "gluten free", "keto"],
    cuisines: ["Mediterranean"],
    prepTime: 10,
  },
  {
    id: 37,
    title: "Thai Larb with Lettuce Cups",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?auto=format&fit=crop&w=600&q=80",
    description: "Spicy Thai ground chicken salad with herbs, served in crisp lettuce cups.",
    calories: 265,
    protein: 28,
    carbs: 8,
    fat: 14,
    diets: ["gluten free", "keto"],
    cuisines: ["Thai"],
    prepTime: 20,
  },
  {
    id: 38,
    title: "Roasted Beet and Goat Cheese Salad",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80",
    description: "Roasted beets with creamy goat cheese, walnuts, and mixed greens with balsamic glaze.",
    calories: 315,
    protein: 12,
    carbs: 25,
    fat: 20,
    diets: ["vegetarian", "gluten free"],
    cuisines: ["French"],
    prepTime: 45,
  },
  {
    id: 39,
    title: "Miso Salmon with Bok Choy",
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=600&q=80",
    description: "Miso-glazed salmon fillet with steamed bok choy and brown rice.",
    calories: 485,
    protein: 42,
    carbs: 35,
    fat: 20,
    diets: ["pescatarian", "gluten free"],
    cuisines: ["Japanese"],
    prepTime: 25,
  },
  {
    id: 40,
    title: "Chickpea Flour Pancakes",
    image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?auto=format&fit=crop&w=600&q=80",
    description: "Protein-rich chickpea flour pancakes with vegetables and fresh herbs.",
    calories: 285,
    protein: 16,
    carbs: 32,
    fat: 10,
    diets: ["vegan", "gluten free"],
    cuisines: ["Indian"],
    prepTime: 20,
  },
  {
    id: 41,
    title: "Turkey and Cranberry Lettuce Wraps",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?auto=format&fit=crop&w=600&q=80",
    description: "Lean turkey with dried cranberries and celery wrapped in butter lettuce.",
    calories: 225,
    protein: 26,
    carbs: 15,
    fat: 8,
    diets: ["gluten free", "keto"],
    cuisines: ["American"],
    prepTime: 15,
  },
  {
    id: 42,
    title: "Ratatouille with Herbs",
    image: "https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?auto=format&fit=crop&w=600&q=80",
    description: "Traditional French vegetable stew with eggplant, zucchini, peppers, and fresh herbs.",
    calories: 185,
    protein: 6,
    carbs: 28,
    fat: 8,
    diets: ["vegan", "gluten free"],
    cuisines: ["French"],
    prepTime: 50,
  },
  {
    id: 43,
    title: "Shrimp and Avocado Salad",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80",
    description: "Grilled shrimp with avocado, cucumber, and citrus dressing over mixed greens.",
    calories: 285,
    protein: 28,
    carbs: 12,
    fat: 16,
    diets: ["pescatarian", "gluten free", "keto"],
    cuisines: ["Mexican"],
    prepTime: 20,
  },
  {
    id: 44,
    title: "Mushroom and Barley Risotto",
    image: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?auto=format&fit=crop&w=600&q=80",
    description: "Creamy barley risotto with mixed mushrooms and fresh thyme.",
    calories: 365,
    protein: 12,
    carbs: 58,
    fat: 10,
    diets: ["vegetarian"],
    cuisines: ["Italian"],
    prepTime: 45,
  },
  {
    id: 45,
    title: "Coconut Curry Lentil Soup",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80",
    description: "Rich coconut curry soup with red lentils, spinach, and aromatic spices.",
    calories: 325,
    protein: 16,
    carbs: 42,
    fat: 12,
    diets: ["vegan", "gluten free"],
    cuisines: ["Thai"],
    prepTime: 35,
  },
  {
    id: 46,
    title: "Grilled Chicken Caesar Salad",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80",
    description: "Grilled chicken breast over romaine lettuce with homemade Caesar dressing and parmesan.",
    calories: 385,
    protein: 35,
    carbs: 12,
    fat: 22,
    diets: ["gluten free", "keto"],
    cuisines: ["American"],
    prepTime: 20,
  },
  {
    id: 47,
    title: "Stuffed Acorn Squash",
    image: "https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?auto=format&fit=crop&w=600&q=80",
    description: "Roasted acorn squash stuffed with wild rice, cranberries, and pecans.",
    calories: 385,
    protein: 8,
    carbs: 68,
    fat: 12,
    diets: ["vegan", "gluten free"],
    cuisines: ["American"],
    prepTime: 60,
  },
  {
    id: 48,
    title: "Tuna Nicoise Salad",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80",
    description: "Classic French salad with seared tuna, hard-boiled eggs, olives, and green beans.",
    calories: 425,
    protein: 38,
    carbs: 18,
    fat: 24,
    diets: ["pescatarian", "gluten free"],
    cuisines: ["French"],
    prepTime: 25,
  },
  {
    id: 49,
    title: "Veggie-Packed Smoothie Bowl",
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=600&q=80",
    description: "Green smoothie bowl with spinach, banana, berries, and topped with granola and seeds.",
    calories: 315,
    protein: 12,
    carbs: 58,
    fat: 8,
    diets: ["vegan", "gluten free"],
    cuisines: ["American"],
    prepTime: 10,
  },
  {
    id: 50,
    title: "Herb-Roasted Chicken Thighs",
    image: "https://images.unsplash.com/photo-1532636875304-0c89119d9b4d?auto=format&fit=crop&w=600&q=80",
    description: "Juicy chicken thighs roasted with herbs, served with roasted Brussels sprouts.",
    calories: 445,
    protein: 38,
    carbs: 15,
    fat: 28,
    diets: ["gluten free", "keto"],
    cuisines: ["American"],
    prepTime: 45,
  },
];